import './minecraft/minecraft-backend.test.js'
import './speech/speech.test.js'
import './integration/scenario-runner.test.js'
import './integration/paper-process-server.test.js'
import './telemetry/debug-state.test.js'
import './models/agent-service-client.test.js'
import './companion/runtime.test.js'
